### ISSUE TITLE
Ability to render image of local STL (filepath instead of URL)

### ISSUE THREAD

**Issue by Kage-Yami** [sunny/craster#11]
Hi. I was hoping to use this tool as part of a pipeline I have; however, it seems that it requires the input to be a URL. It'd be nice if I could pass in a local filepath to use as the STL input. 

Using a `file://` URL at first appears to "work", but it actually results in a 100% transparent PNG.

**Comment by sunny** [comment]
Great idea @Kage-Yami! I added a `--path` (instead of `--url`) argument to do exactly that. 🎉

**Comment by Kage-Yami** [comment]
@sunny Thanks! It's working like a charm.

I'm using it in a hobby project of mine: https://kage-yami.gitlab.io/3d-models 
Utilising GitLab CI/CD to render out models (from OpenSCAD) and build a static website to showcase them - so `craster` is providing me the thumbnails on the index page. :smiley:

**Comment by sunny** [comment]
Ohhh, cool project! It's really cool to see the SCAD code right next to the model.

I am no designer but I have started playing with `.scad` files to see how we can add a file customizer on cults3d.com. Fun stuff 😀
