### ISSUE TITLE
Convert this to es6 please

### ISSUE THREAD

**Issue by jimmywarting** [sunny/craster#2]

**Comment by sunny** [comment]
Hi Jimmy! Thank you for the suggestion.

Why would you need to have it in ES6? Would you like to contribute to the code, perhaps? Or use it is a module from within an ES6 project? What would the use-case be?

**Comment by jimmywarting** [comment]
I want to use it from a project from which I already writing ES6.
maybe to contribute also.
It's also that CoffeeScript adds a unnecessary build step. And makes debugging harder.
ES6 syntax isn't that different from CoffeeScript with it's fat arrow function and `;` as optional es6 has classes also...

It's also that CoffeeScript will also always be one step behind
CoffeeScript is implementing their own take on JavaScript. Some of the things from dose not work in CoffeeScript like async/await

Technologies that have competing spec / community driven development have a history of failing; take: Flash, SilverLight, Google Gears, the list goes on. If you have a large code base, picking CoffeeScript is something your going to be living with for a long time. I can take a bet in 3 years JavaScript will still be around without a doubt.

Its also worth noting that they have built some things like module system and as soon as the spec came out they ditched it and started using that. Have fun updating!

**Comment by sunny** [comment]
Alright then! I'd happily accept a PR that removes CoffeeScript from the project in favor of ES6.

Would you be willing to do it, since you suggested in the first place?

**Comment by sunny** [comment]
Done in ddcf5e1 ! \o/
